import {NextResponse} from 'next/server';
import {z} from 'zod';
import {getViewer} from '@/lib/auth';
import {mediaLimit} from '@/lib/entitlements';

const createSchema=z.object({kind:z.enum(['logo','project','trade']),storage_path:z.string().min(10).max(500),public_url:z.string().url().max(1000),caption:z.string().trim().max(180).optional(),supplier_profile_id:z.string().uuid().nullable().optional()});

export async function POST(request:Request){const {user,profile,supabase}=await getViewer();if(!user||!profile||profile.role==='admin')return NextResponse.json({error:'Business or supplier account required.'},{status:403});const parsed=createSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:'Invalid image record.'},{status:400});if(!parsed.data.storage_path.startsWith(`${user.id}/`))return NextResponse.json({error:'Invalid storage path.'},{status:403});if(profile.role==='supplier'){const {data:company}=await supabase.from('supplier_profiles').select('id').eq('owner_id',user.id).maybeSingle();if(!company||company.id!==parsed.data.supplier_profile_id)return NextResponse.json({error:'Company ownership required.'},{status:403});}else if(parsed.data.supplier_profile_id)return NextResponse.json({error:'Business media cannot be attached to a supplier.'},{status:400});const {count}=await supabase.from('profile_media').select('*',{count:'exact',head:true}).eq('owner_id',user.id);const limit=mediaLimit(profile.role,null);if((count??0)>=limit)return NextResponse.json({error:`The launch workspace supports ${limit} company images.`},{status:400});const {data,error}=await supabase.from('profile_media').insert({owner_id:user.id,...parsed.data}).select('*').single();return error?NextResponse.json({error:'Unable to save image.'},{status:400}):NextResponse.json({media:data});}

export async function DELETE(request:Request){const {user,supabase}=await getViewer();if(!user)return NextResponse.json({error:'Sign in required.'},{status:401});const parsed=z.object({id:z.string().uuid()}).safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:'Invalid image.'},{status:400});const {data}=await supabase.from('profile_media').select('storage_path').eq('id',parsed.data.id).eq('owner_id',user.id).maybeSingle();if(!data)return NextResponse.json({error:'Image not found.'},{status:404});const {error}=await supabase.from('profile_media').delete().eq('id',parsed.data.id).eq('owner_id',user.id);if(error)return NextResponse.json({error:'Unable to remove image.'},{status:400});await supabase.storage.from('company-media').remove([data.storage_path]);return NextResponse.json({ok:true});}
