import {BadgeCheck,Building2,FileCheck2,Globe2,Mail,ShieldCheck} from 'lucide-react';
import {TrustReviewActions} from '@/components/TrustReviewActions';
import styles from './TrustReviewExperience.module.css';

type Verification={id:string;legal_company_name:string;account_role:string;work_email:string;business_phone:string;business_website:string|null;registration_number:string|null;supporting_details:string|null;domain_match:boolean;status:string;created_at:string;profileCompany?:string|null};
type Review={id:string;project_name:string|null;project_type:string|null;body:string|null;created_at:string;reviewerCompany:string;supplierName:string;relationshipContext:string|null};

export function TrustReviewExperience({verifications,reviews}:{verifications:Verification[];reviews:Review[]}){
  return <div className={styles.page}><header><span><ShieldCheck/> NETWORK TRUST</span><h1>Company and review verification</h1><p>Manually confirm company identity before buyers can influence supplier scores, then moderate written reviews before publication.</p></header><section><div className={styles.sectionTitle}><span>01</span><div><h2>Company verification requests</h2><p>Check the work email, website, public business registration, phone, and supporting details.</p></div><b>{verifications.length} pending</b></div><div className={styles.cards}>{verifications.map(item=><article key={item.id}><header><div className={styles.icon}><Building2/></div><div><small>{item.account_role.toUpperCase()} COMPANY</small><h3>{item.legal_company_name}</h3><p>Account company: {item.profileCompany||'Not provided'}</p></div><span className={item.domain_match?styles.match:styles.reviewNeeded}>{item.domain_match?'DOMAIN MATCH':'MANUAL CHECK'}</span></header><div className={styles.facts}><p><Mail/><span>Work email<b>{item.work_email}</b></span></p><p><Globe2/><span>Website<b>{item.business_website||'Not supplied'}</b></span></p><p><FileCheck2/><span>Registration / license<b>{item.registration_number||'Not supplied'}</b></span></p><p><Building2/><span>Business phone<b>{item.business_phone}</b></span></p></div><blockquote>{item.supporting_details}</blockquote><footer><small>Submitted {new Intl.DateTimeFormat('en-US',{dateStyle:'medium'}).format(new Date(item.created_at))}</small><TrustReviewActions kind="verification" id={item.id}/></footer></article>)}{!verifications.length?<div className={styles.empty}>No company verification requests are waiting.</div>:null}</div></section><section><div className={styles.sectionTitle}><span>02</span><div><h2>Written review moderation</h2><p>Every review comes from a verified builder account with a direct-relationship attestation. Approve only credible, relevant feedback.</p></div><b>{reviews.length} pending</b></div><div className={styles.cards}>{reviews.map(review=><article key={review.id}><header><div className={styles.icon}><BadgeCheck/></div><div><small>VERIFIED BUILDER COMPANY</small><h3>{review.reviewerCompany}</h3><p>Reviewing {review.supplierName}</p></div></header><div className={styles.reviewMeta}><span>{review.project_name||'Business relationship'}</span><span>{review.project_type||'Engagement type not supplied'}</span></div><blockquote>{review.body}</blockquote><p className={styles.context}><b>Relationship context:</b> {review.relationshipContext||'Not supplied'}</p><footer><small>Submitted {new Intl.DateTimeFormat('en-US',{dateStyle:'medium'}).format(new Date(review.created_at))}</small><TrustReviewActions kind="review" id={review.id}/></footer></article>)}{!reviews.length?<div className={styles.empty}>No written reviews are waiting for moderation.</div>:null}</div></section></div>;
}
