import Link from 'next/link';
import {Sidebar} from '@/components/Sidebar';
import {WorkspaceHeading} from '@/components/WorkspaceHeading';
import {requireRole} from '@/lib/auth';

export default async function Page(){
  const {user,profile,supabase}=await requireRole(['supplier']);
  const {data:company}=await supabase.from('supplier_profiles').select('*').eq('owner_id',user.id).maybeSingle();
  const [{count:saves},{data:reviews},{count:notifications}]=company?await Promise.all([
    supabase.from('saved_suppliers').select('*',{count:'exact',head:true}).eq('supplier_profile_id',company.id),
    supabase.from('reviews').select('id,project_name,body,verified,created_at').eq('supplier_profile_id',company.id).eq('is_public',true).order('created_at',{ascending:false}).limit(5),
    supabase.from('notifications').select('*',{count:'exact',head:true}).eq('user_id',user.id).is('read_at',null),
  ]):[{count:0},{data:[]},{count:0}] as any;
  return <main className="shell"><Sidebar role="supplier"/><section className="workspace"><WorkspaceHeading eyebrow="SUPPLIER WORKSPACE" title={company?.name||profile.company_name||'Your company'} description="Your live TradeStak reputation and company presence." action={<Link className="button" href="/supplier/profile">Edit company profile</Link>}/>{company?<><div className="metricGrid"><div className="metric"><small>TradeStak score</small><strong>{company.score??'—'}</strong><span>{company.review_count?`${company.review_count} evaluations`:'Awaiting evaluations'}</span></div><div className="metric"><small>Builder saves</small><strong>{saves??0}</strong><span>Real builder interest</span></div><div className="metric"><small>Verification</small><strong style={{fontSize:20}}>{company.verified?'Verified':'Unverified'}</strong><span>{company.claimed?'Ownership confirmed':'Ownership pending'}</span></div><div className="metric"><small>Unread notifications</small><strong>{notifications??0}</strong><span>Account activity</span></div></div><div className="dashboardGrid"><section className="panel"><div className="eyebrow">PERFORMANCE</div><h2>Reputation breakdown</h2><div className="metricGrid" style={{gridTemplateColumns:'repeat(3,1fr)'}}><div className="metric"><small>Quality</small><strong>{company.quality_score??'—'}</strong></div><div className="metric"><small>Delivery</small><strong>{company.delivery_score??'—'}</strong></div><div className="metric"><small>Communication</small><strong>{company.communication_score??'—'}</strong></div></div></section><aside className="panel"><div className="eyebrow">PUBLIC FEEDBACK</div><h2>Recent reviews</h2>{(reviews??[]).map((review:any)=><article key={review.id} style={{borderTop:'1px solid var(--line)',padding:'14px 0'}}><b>{review.project_name||'Builder evaluation'}</b><p>{review.body||'Scores submitted without a written review.'}</p><small>{review.verified?'TradeStak verified':'Builder submitted'}</small></article>)}{!reviews?.length?<div className="empty">No public builder feedback yet.</div>:null}</aside></div></>:<div className="panel empty"><h2>Create your company presence.</h2><p>Your account is active, but no company profile is connected yet. Complete onboarding to publish your company.</p><Link className="button" href="/supplier/profile">Complete company profile</Link></div>}</section></main>;
}
